packages:
  - packages/*
  - apps/*

catalog:
  '@biomejs/biome': ^1.9.4
  knip: ^5.73.4
  nx: ^22.2.2
  syncpack: ^13.0.4
  tsup: ^8.5.1
  typescript: 5.9.3
  vitest: ^4.0.15

catalogMode: strict

ignoredBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - nx

minimumReleaseAge: 2880
