packages:
  - packages/*
  - apps/*

catalog:
  '@biomejs/biome': ^2.3.11
  knip: ^5.81.0
  nx: ^22.3.3
  syncpack: ^13.0.4
  tsup: ^8.5.1
  typescript: 5.9.3
  vitest: ^4.0.17

catalogMode: strict

ignoredBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - nx

minimumReleaseAge: 2880
